Repository dev-AshishRanjan/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#1 PR for Js code
  CONTRIBUTORS.md
  Database/Hello World.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/S

#2 hw
  CONTRIBUTORS.md
  Database/Hello_World.cpp
Labels: size/S

#3 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, hacktoberfest-accepted, size/S

#4 Create HacktoberFest_2023
  Database/HacktoberFest_2023
Labels: hacktoberfest, hacktoberfest-accepted, size/XS

#5 Add PHP "Hello_World"
  CONTRIBUTORS.md
  Database/Hello_World.php
Labels: hacktoberfest, hacktoberfest-accepted, size/S

#6 Added Hello_world.html
  CONTRIBUTORS.md
  Database/Hello_World.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/S

#7 Create Hello_World.sh
  Database/Hello_World.sh
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XS

#8 Added information
  CONTRIBUTORS.md
  Database/HelloWorld.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/S
